# Generated by Django 3.2.9 on 2021-12-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='lucky_cards',
            field=models.ManyToManyField(related_name='lucky_cards', to='luckydraw.Cards'),
        ),
    ]
