# Generated by Django 3.2.9 on 2021-12-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0002_alter_coupon_lucky_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='created_by',
            new_name='lucky_created_by',
        ),
    ]
