# Generated by Django 3.2.9 on 2021-12-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0003_rename_created_by_coupon_lucky_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_card_id', to='luckydraw.cards')),
                ('winner_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_coupon_id', to='luckydraw.coupon')),
            ],
        ),
    ]
