# Generated by Django 3.2.9 on 2021-12-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydraw', '0008_auto_20220101_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletednumber',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
