# Generated by Django 3.1.2 on 2020-11-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cards_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
