# Generated by Django 3.1.2 on 2020-11-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cards_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cards',
            field=models.ManyToManyField(to='main.Cards'),
        ),
    ]
