# Generated by Django 3.1.2 on 2020-11-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201128_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
