# Generated by Django 3.1.2 on 2020-12-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cards_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link_exist', models.BooleanField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
