# Generated by Django 3.1.2 on 2021-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_siteannouncements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
