# Generated by Django 3.1.2 on 2021-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210929_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='bill_amount',
            field=models.CharField(max_length=200),
        ),
    ]
