# Generated by Django 3.1.2 on 2021-10-05 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211002_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='bill_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
